import Link from "next/link";

export function Header({active}:{active?:string}) {
  return <header className="site-header"><div className="shell nav">
    <Link href="/" className="brand"><span className="brand-mark">T</span><span>Threads <b>Video Maker</b></span></Link>
    <nav aria-label="Điều hướng chính"><Link className={active==="home"?"active":""} href="/">Giới thiệu</Link><Link className={active==="products"?"active":""} href="/san-pham">Sản phẩm</Link><Link className={active==="windows"?"active":""} href="/windows">Windows</Link><Link className={active==="macos"?"active":""} href="/macos">macOS</Link><Link className={active==="updates"?"active":""} href="/cap-nhat">Cập nhật</Link><Link className={active==="guide"?"active":""} href="/huong-dan">Hướng dẫn</Link></nav>
    <Link href="/macos" className="nav-download">Tải ứng dụng <span>↓</span></Link>
  </div></header>;
}

export function Footer(){return <footer><div className="shell footer-inner"><Link href="/" className="brand inverse"><span className="brand-mark">T</span><span>Threads <b>Video Maker</b></span></Link><p>Công cụ tạo video hội thoại dành cho người làm nội dung.</p><div className="footer-links"><Link href="/san-pham">Sản phẩm</Link><Link href="/windows">Windows</Link><Link href="/macos">macOS</Link><Link href="/cap-nhat">Cập nhật</Link><Link href="/huong-dan">Hướng dẫn</Link></div></div><div className="shell copyright">© 2026 Threads Video Maker. Made for short-form creators.</div></footer>}

export function ProductPreview(){return <div className="product-stage" aria-label="Minh họa giao diện ứng dụng"><div className="glow"/><div className="app-window"><div className="window-bar"><div className="dots"><i/><i/><i/></div><span>Threads Video Maker</span><b>⌁</b></div><div className="app-body"><aside><div className="side-title">KỊCH BẢN</div><div className="side-card active"><small>01 · THREADS</small><b>Một ý tưởng hay bắt đầu từ...</b><span>4.2 giây</span></div><div className="side-card"><small>02 · MESSENGER</small><b>Đoạn hội thoại tiếp theo</b><span>3.8 giây</span></div><div className="side-card"><small>03 · VIDEO</small><b>Media minh họa</b><span>5.0 giây</span></div><button>＋ Thêm card</button></aside><div className="canvas"><div className="phone-preview"><div className="thread-head"><span className="fake-avatar"/><div><b>minh.content</b><small>vừa xong</small></div><i>•••</i></div><p>Bạn không cần chỉnh từng lớp để tạo một video short hấp dẫn.</p><div className="media-placeholder"><span>▶</span><small>VIDEO · 00:05</small></div><div className="reaction">♡　◯　↗</div></div><div className="timeline"><span className="play">▶</span><div><i/><b style={{width:"68%"}}/></div><small>00:08 / 00:24</small></div></div></div></div><div className="floating-chip chip-one">✦ TTS đã sẵn sàng</div><div className="floating-chip chip-two">✓ Xuất MP4 9:16</div></div>}

export function DownloadPage({platform}:{platform:"macos"|"windows"}){
  const mac=platform==="macos";
  const release="https://github.com/NemCua/audio/releases/download/desktop-v1.1.3";
  return <main><Header active={platform}/><section className="download-hero"><div className="shell download-grid"><div><div className="eyebrow"><span/> Phiên bản dành cho {mac?"macOS":"Windows"}</div><h1>Tải Threads Video Maker<br/>cho <em>{mac?"macOS":"Windows"}</em>.</h1><p>{mac?"Chọn đúng phiên bản cho Mac Apple Silicon hoặc Intel. Ứng dụng đã tích hợp sẵn FFmpeg và thư viện media để bạn bắt đầu ngay.":"Tải bộ cài tiêu chuẩn hoặc phiên bản Portable dành cho Windows 10/11 64-bit."}</p><div className="download-options">{mac?<><a className="button primary" href={`${release}/Threads.Video.Maker-1.1.3-arm64.dmg`}>↓ Tải cho Apple Silicon</a><a className="button secondary" href={`${release}/Threads.Video.Maker-1.1.3-x64.dmg`}>Tải cho Mac Intel</a></>:<><a className="button primary" href={`${release}/Threads.Video.Maker-Setup-1.1.3-x64.exe`}>↓ Tải bộ cài Windows</a><a className="button secondary" href={`${release}/Threads.Video.Maker-Portable-1.1.3-x64.exe`}>Tải bản Portable</a></>}</div><div className="system-note"><span>{mac?"Yêu cầu: macOS 12 trở lên":"Yêu cầu: Windows 10/11 64-bit"}</span><span>{mac?"Hỗ trợ: Apple Silicon và Intel x64":"Có bản Setup và Portable"}</span></div></div><div className={`platform-art ${mac?"mac":"win"}`}><div className="platform-logo" aria-hidden="true">{mac?<svg viewBox="0 0 24 24"><path d="M12.152 6.896c-.948 0-2.415-1.078-3.96-1.04-2.04.027-3.91 1.183-4.961 3.014-2.117 3.675-.546 9.103 1.519 12.09 1.013 1.454 2.208 3.09 3.792 3.039 1.52-.065 2.09-.987 3.935-.987 1.831 0 2.35.987 3.96.948 1.637-.026 2.676-1.48 3.676-2.948 1.156-1.688 1.636-3.325 1.662-3.415-.039-.013-3.182-1.221-3.22-4.857-.026-3.04 2.48-4.494 2.597-4.559-1.429-2.09-3.623-2.324-4.39-2.376-2-.156-3.675 1.09-4.61 1.09zM15.53 3.83c.843-1.012 1.4-2.427 1.245-3.83-1.207.052-2.662.805-3.532 1.818-.78.896-1.454 2.338-1.273 3.714 1.338.104 2.715-.688 3.559-1.701"/></svg>:<svg viewBox="0 0 24 24"><path d="M1 3.25 10.5 2v9.25H1V3.25Zm10.5-1.39L23 0v11.25H11.5V1.86ZM1 12.25h9.5V21L1 19.75v-7.5Zm10.5 0H23V23l-11.5-1.86v-8.89Z"/></svg>}</div><div className="download-card"><span>Threads Video Maker</span><strong>{mac?"macOS · ARM64 / x64":"Windows · x64"}</strong><small>Version 1.1.3</small></div></div></div></section>
    <section className="section shell"><div className="section-heading compact"><div><span className="kicker">Có sẵn trong ứng dụng</span><h2>Một bản cài, đầy đủ công cụ.</h2></div><p>Không cần tải rời từng thành phần. Những tài nguyên cần thiết được đóng cùng ứng dụng.</p></div><div className="included-grid"><article><b>01</b><h3>Engine xuất video</h3><p>FFmpeg được tích hợp để ghép và xuất MP4 trực tiếp trên thiết bị.</p></article><article><b>02</b><h3>Thư viện media</h3><p>Âm thanh, sticker, avatar và tài nguyên mẫu có sẵn ngay khi mở app.</p></article><article><b>03</b><h3>Dự án JSON</h3><p>Lưu, nạp lại và tiếp tục chỉnh sửa dự án mà không phải làm lại từ đầu.</p></article></div></section>
    {mac&&<section className="install-section"><div className="shell install-grid"><div><span className="kicker light">Cài đặt nhanh</span><h2>Ba bước để bắt đầu.</h2></div><ol><li><span>1</span><div><b>Tải file DMG</b><p>Nhấn nút tải và chờ file hoàn tất.</p></div></li><li><span>2</span><div><b>Kéo app vào Applications</b><p>Mở DMG rồi kéo Threads Video Maker vào thư mục Applications.</p></div></li><li><span>3</span><div><b>Mở và đăng nhập</b><p>Khởi động ứng dụng, đăng nhập và bắt đầu tạo dự án.</p></div></li></ol></div></section>}
    <Footer/></main>
}
